util/cbfstool/flashmap/fmap.c: Fix buffer overflow
While compiling coreboot/tooling I got the following error:
In function 'fmap_find_test',
    inlined from 'fmap_test' at util/cbfstool/flashmap/fmap.c:629:6:
util/cbfstool/flashmap/fmap.c:593:9: error: 'memcpy' reading between 57 and 2752527 bytes from a region of size 56 [-Werror=stringop-overread]
  593 |         memcpy(&buf[total_size - fmap_size(fmap) + 1],
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  594 |                fmap,
      |                ~~~~~
  595 |                fmap_size(fmap) + 1);
      |                ~~~~~~~~~~~~~~~~~~~~
In function 'fmap_create',
    inlined from 'fmap_create_test' at util/cbfstool/flashmap/fmap.c:344:9,
    inlined from 'fmap_test' at util/cbfstool/flashmap/fmap.c:624:17:
util/cbfstool/flashmap/fmap.c:258:16: note: source object of size 56 allocated by 'malloc'
  258 |         fmap = malloc(sizeof(*fmap));
      |                ^~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [util/mec152x/Makefile.mk:20: /cb-build/coreboot-gerrit.0/gcc/sharedutils/mec152x/fmap.o] Error 1

The error is in one of the tests inside fmap.c, which in turn is build
by the util/mec152x tooling. I am however unsure why only this tooling
causes the file not to compile, considering other toolings such as
fmaptool should also cause the compiler issue.

While the code is meant to simulate an "overflow" of some kind, its not
meant to overflow the memcpy operation of "buf" buffer.

Signed-off-by: Maximilian Brune <maximilian.brune@9elements.com>
Change-Id: If15071a3c4b54d90495f400fddf22a9a698f85a5
Reviewed-on: https://review.coreboot.org/c/coreboot/+/91885
Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Reviewed-by: Patrick Rudolph <patrick.rudolph@9elements.com>