cbfstool: Improve lexer error message
Instead of just "syntax error" print the line number and the line
that caused the problem.

Example new output:

error: syntax error in line 6:
>   COREBOOT_TS(CBFS|ALT_BOOT) 1M

Change-Id: Ibec3241a5fda16788c54d135f2e326955b9acb78
Signed-off-by: Patrick Rudolph <patrick.rudolph@9elements.com>
Reviewed-on: https://review.coreboot.org/c/coreboot/+/91853
Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Reviewed-by: Angel Pons <th3fanbus@gmail.com>